### ISSUE TITLE
jniloader doesn't build out of the box

### ISSUE THREAD

**Issue by fboudra** [fommil/jniloader#7]
after a fresh clone, tried to run mvn clean install:
```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /home/user/jniloader/src/main/java/com/github/fommil/jni/JniLoader.java:[62,9]
cannot find symbol
  symbol:   variable log
  location: class com.github.fommil.jni.JniLoader
```

See https://projectlombok.org/features/Log.html
the @Log annotation should be causing lombok to generate the logger field "log".
for sone reason, maven is not invoking the lombok annotation processor.

I tried to rename src/main/java directory to src/main/lombok but it still fails to build properly.

Any chance to fix the issue and eventually make a new release?

**Comment by fommil** [comment]
This doesn't look like a bug in `netlib-java`, it looks more like a support request for your machine.

Unfortunately I simply don't have the time to help out with these sorts of requests without a commercial contract in place. Most of the information that you need to solve this problem is available in the README and a seasoned GNU/Linux admin would be able to solve it for you. I'm not interested in making any more binary builds available for custom distributions.

If you'd be interested in getting your organisation to sponsor me to work on [the `netlib-java` roadmap](https://github.com/fommil/netlib-java/wiki/CallForFunding), to add support for additional native libraries or hardware (e.g. graphics cards and FPGAs) that is something I'd be interested in on a commercial basis.

**Comment by fboudra** [comment]
I'm not sure what you mean... it has nothing to do with netlib-java, it is jniloader.

git clone https://github.com/fommil/jniloader.git
cd jniloader
mvn clean install

and it fails to build.

How is it related to netlib-java or any commercial support?

**Comment by fommil** [comment]
It's all part of the same project.

**Comment by fboudra** [comment]
In other words, jniloader doesn't builds on its own, it should be built in netlib-java. Due to the lack of any build instructions, it isn't clear. Especially when jniloader lives into a separate repository.
